### PR TITLE
Remove duplicate header

### PR DESCRIPTION
**Pull request by PatrickMcSweeny**
This is a possible solution to exercism/exercism#3812. Basically, it removes the first line from the markdown if the first line consists of nothing more than a '#' character followed by the title of the exercise.

### CODE REVIEW

**Comment by PatrickMcSweeny** [comment]
Sidenote: I expected that making this change would cause one of the solution model tests to fail, but it kept passing. I opened exercism/exercism#4202 to raise this issue.

**Comment by PatrickMcSweeny** [comment]
I'll take a stab at writing a test.

**Comment by iHiD** [comment]
Thanks. If you struggle for any reason, I don't mind adding it - just shout! :)

**Comment by PatrickMcSweeny** [comment]
@iHiD You should probably go ahead and the test, I don't think I am going to get very far.

**Comment by iHiD** [comment]
@PatrickMcSweeny I've [added a test](https://github.com/exercism/website/pull/321/commits/01929928d02f94341c0687f8d1852a7a2fbaefad). I'll merge once it's green. Thank you!

**Comment by iHiD** [comment]
This was really pissing me off as a problem on the site, so I really appreciate it. Thanks :)

**Pull request merged**
