### PR TITLE
Store scroll position for RHS panel in editor

### PR DESCRIPTION
**Pull request by kntsoriano**
@SleeplessByte How do you recommend we debounce the `onScroll` event?

https://github.com/exercism/v3-project-management/issues/207

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I can't see the linked issue. Can you copy it in?

**Comment by iHiD** [comment]
@SleeplessByte https://www.loom.com/share/46e28bb5943a47c0ac3ac4af8832848f

**Comment by iHiD** [comment]
One general thing to add to this is that I'm going to add `scroll-behavior: smooth` generally to the CSS so we'll have to get around that for this. ~I'll push that onto main for you so its there.~ _(Was already there)_

**Comment by SleeplessByte** [comment]
The far easier, cross-browser, ánd accessible solution is to not replace the _content_ of the scrollable pane, but have the three panes mounted / exist in DOM (but invisible), and have the tabs change which one is showing.

**Comment by iHiD** [comment]
@kntsoriano I agree with what @SleeplessByte is saying here. Do you want to refactor to do that (three panels, with one having an `active` css class at a time). And I can tweak any CSS that breaks as a result of it?

**Comment by SleeplessByte** [comment]
(It also reduces the JS by a lot 🗡️)

**Pull request closed without merging**
