### PR TITLE
Use heading tag for exercise titles to improve accessibility

### PR DESCRIPTION
**Pull request by PatrickMcSweeny**
Partial fix for exercism/exercism#4522.

Screenshot:

screenshot from 2019-01-24 21-41-16

### CODE REVIEW

**Comment by iHiD** [comment]
Thank you :)

**Comment by PatrickMcSweeny** [comment]
@iHiD Was there any particular reason for undoing these changes?

**Comment by iHiD** [comment]
@PatrickMcSweeny Yes - it broke the styling on pages where there was styling defined for h2s. For example on the external track pages, the little exercise widgets at the bottom ended up with huge centralised headings.

**Comment by PatrickMcSweeny** [comment]
@iHiD Would you like me to work on a pull request to fix the issue with heading tags? I think it's important to use semantic tags to improve accessibility.

**Comment by iHiD** [comment]
Hi @PatrickMcSweeny. Not at the moment but thank you. I don't have the brainspace to thoroughly review PRs enough right now, with everything else that's going on in Exercism :) 

Also, the exercise widgets that are changed have different heading levels in different places, so having `h2` everywhere wouldn't be appropriate. As this also effects external pages, it's important to consider the SEO offsets. So there's more thought required for this than just updating the HTML/CSS - thought I don't have time for atm.

**Pull request merged**
