### PR TITLE
Remove cache time from mentoring queue

### LINKED ISSUE #5639: left -right panel sync mismatch in mentoring queue
Mentored a Rust - Clock exercise. After closing the solution the Mentoring Queue showed 1 Clock exercise in the right panel but no solution in the left panel. I refreshed. Now it shows 0 Clock exercises, even though "Only show exercises that need mentoring" is checked. 
err_1

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/exercism/issues/5639.

This is not a really good solution, but I don't know how else to fix it.

### CODE REVIEW

**Comment by iHiD** [comment]
@SleeplessByte Any thoughts on this (the problem as much as the solution)?

**Comment by kntsoriano** [comment]
As a background, when I go to `/mentoring/queue`, the query does not seem to remount. It is forever marked stale and won't refetch. I don't understand why it doesn't remount. I might not understand something about react-query. `fetchOnMount` is also set to true.

**Comment by iHiD** [comment]
Should we merge this anyway @kntsoriano and then follow up when DJ has time? If so, could you make the tests green pls?

**Comment by kntsoriano** [comment]
@iHiD Cool. I'm okay to merge this.

**Pull request merged**
