### PR TITLE
Add new legendary badges

### PR DESCRIPTION
**Pull request by ErikSchierboom**
- Add architect badge
- Add bard badge
- Add begetter badge
- Add moss badge
- Add tooling-pioneer badge
- Update badge factory

I've made all the badges `ultimate` badges, as they're exceedingly rare.

### CODE REVIEW

**Comment by iHiD** [comment]
### Architect

```svg
<svg width="700" height="700" viewBox="0 0 700 700" fill="none" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M0 35V665H700V35H0ZM583.333 58.3333V81.6667H116.667V58.3333H583.333ZM630 595H70V105H630V595ZM23.3333 58.3333H93.3333V81.6667H46.6667V128.333H23.3333V58.3333ZM23.3333 151.667H46.6667V548.333H23.3333V151.667ZM23.3333 641.667V571.667H46.6667V618.333H93.3333V641.667H23.3333ZM116.667 641.667V618.333H583.333V641.667H116.667ZM676.667 641.667H606.667V618.333H653.333V571.667H676.667V641.667ZM676.667 548.333H653.333V151.667H676.667V548.333ZM676.667 58.3333V128.333H653.333V81.6667H606.667V58.3333H676.667Z" fill="black"/>
<path d="M291.666 315H105C98.557 315 93.333 320.224 93.333 326.667V560C93.333 563.094 94.5622 566.063 96.7497 568.25C98.9372 570.437 101.906 571.667 105 571.667H291.666C294.76 571.667 297.729 570.437 299.916 568.25C302.104 566.062 303.333 563.094 303.333 560V326.667C303.333 323.573 302.104 320.604 299.916 318.417C297.729 316.229 294.76 315 291.666 315ZM116.666 385H280V478.333H116.666V385ZM280 548.333H116.666V501.667H280V548.333ZM116.666 361.667V338.333H280V361.667H116.666Z" fill="black"/>
<path d="M499.76 361.826L359.76 385.159C353.406 386.222 349.114 392.227 350.166 398.575L373.5 538.575C374.437 544.2 379.302 548.325 385.005 548.331C385.651 548.336 386.297 548.279 386.932 548.169L526.932 524.836C533.281 523.773 537.573 517.768 536.521 511.42L513.187 371.42C512.677 368.368 510.979 365.639 508.458 363.842C505.942 362.045 502.812 361.321 499.76 361.826V361.826ZM394.594 523.253L375.088 406.258L492.083 386.753L511.588 503.747L394.594 523.253Z" fill="black"/>
<path d="M351.906 151.826L211.906 128.493C208.854 127.967 205.718 128.681 203.192 130.483C200.671 132.29 198.979 135.024 198.489 138.087L175.156 278.087C174.104 284.436 178.395 290.441 184.749 291.503L324.749 314.836C325.38 314.946 326.02 314.998 326.661 314.998C332.359 314.987 337.218 310.867 338.15 305.242L361.484 165.242C362.541 158.894 358.255 152.894 351.906 151.826V151.826ZM317.072 289.92L200.078 270.414L219.583 153.42L336.578 172.925L317.072 289.92Z" fill="black"/>
<path d="M583.333 478.333H606.666V501.666H583.333V478.333Z" fill="black"/>
<path d="M548.333 525H571.666V548.333H548.333V525Z" fill="black"/>
<path d="M396.667 140V326.666C396.667 329.76 397.896 332.729 400.084 334.916C402.271 337.104 405.24 338.333 408.334 338.333H595C598.094 338.333 601.063 337.104 603.25 334.916C605.438 332.729 606.667 329.76 606.667 326.666V140C606.667 136.906 605.438 133.937 603.25 131.75C601.063 129.562 598.094 128.333 595 128.333H408.334C401.891 128.333 396.667 133.557 396.667 140ZM420 151.666H583.334V315H420V151.666Z" fill="black"/>
<path d="M443.333 175H536.666V198.333H443.333V175Z" fill="black"/>
<path d="M443.333 221.667H513.333V245H443.333V221.667Z" fill="black"/>
<path d="M443.333 268.333H501.666V291.666H443.333V268.333Z" fill="black"/>
<path d="M536.667 221.667H560V245H536.667V221.667Z" fill="black"/>
<path d="M96.7607 178.427L131.766 143.422L148.266 159.922L113.261 194.927L96.7607 178.427Z" fill="black"/>
<path d="M96.7461 236.746L143.413 190.079L159.913 206.579L113.246 253.246L96.7461 236.746Z" fill="black"/>
</g>
</svg>
```

**Comment by iHiD** [comment]
### Bard

```svg
<svg width="700" height="700" viewBox="0 0 700 700" fill="none" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M682.124 441.027L638.911 380.044L675.973 362.266C697.492 351.382 706.154 325.015 695.264 303.473C684.393 281.954 658.02 273.287 636.761 284.043L585.063 308.855C572.2 297.451 556.65 289.443 539.569 285.653V233.336C539.569 209.216 519.939 189.592 495.825 189.592L451.953 189.586C456.892 174.102 459.634 157.269 459.634 139.637C459.634 136.834 459.537 134.068 459.398 131.314C464.961 129.268 468.95 123.965 468.95 117.682V102.084C468.95 45.8039 423.158 0 366.878 0H308.921C265.968 0 231.023 34.9445 231.023 77.8971V117.678C231.023 123.961 235.006 129.263 240.575 131.309C240.436 134.057 240.339 136.83 240.339 139.632C240.339 157.265 243.081 174.098 248.026 189.581H204.155C180.034 189.581 160.404 209.211 160.404 233.326V285.642C135.611 291.145 113.936 305.435 99.2208 326.192L17.8557 441.029C6.33078 454.297 0 471.252 0 488.837V545.415C0 584.046 35.18 608.131 70.2871 612.252C70.3295 612.259 70.3658 612.271 70.4082 612.271C70.729 612.307 71.062 612.374 71.3828 612.41C71.8791 612.464 72.3694 612.489 72.8778 612.489C72.8839 612.489 72.896 612.495 72.9021 612.495V612.489C72.9081 612.489 72.9081 612.495 72.9081 612.495H98.8821C113.948 635.63 134.964 654.879 160.405 667.85V685.404C160.405 693.466 166.93 699.991 174.993 699.991C183.043 699.991 189.568 693.466 189.568 685.404V666.428C189.81 665.992 190.095 665.586 190.289 665.126C190.385 664.89 190.422 664.66 190.507 664.424C191.947 660.374 191.481 656.113 189.568 652.572C188.061 649.77 185.688 647.409 182.577 646.035C179.992 644.951 177.48 643.753 174.993 642.512C169.896 639.994 165.06 637.143 160.405 634.044C151.126 627.864 142.73 620.655 135.43 612.496C132.852 609.608 130.449 606.576 128.143 603.489L161.61 597.908L162.809 597.708C165.672 597.242 168.19 595.922 170.212 594.082C175.932 595.898 182.336 597.127 189.55 597.623C191.917 597.787 194.32 597.92 196.874 597.92C241.848 597.92 277.084 572.304 277.084 539.586C277.084 506.868 241.856 481.252 196.874 481.252C177.057 481.252 162.536 486.361 152.21 494.26L107.92 486.882C123.01 438.705 165.841 400.966 217.425 394.761C230.693 393.024 245.142 393.454 259.432 396.365C274.886 399.289 290.055 394.471 300.405 383.539C326.214 356.844 362.969 344.891 400.594 352.039C418.147 355.32 434.399 363.352 448.05 374.599L375.528 409.398C371.969 408.72 368.319 408.333 364.578 408.333C332.418 408.333 306.244 434.494 306.244 466.667C306.244 498.845 332.418 525 364.578 525C390.273 525 412.094 508.276 419.855 485.159L488.296 452.322C488.441 454.707 488.538 457.086 488.538 459.368C488.502 473.036 485.935 486.111 481.311 498.18C467.897 501.316 455.641 506.824 445.81 514.39C430.242 526.381 421.961 542.67 423.093 559.122C423.099 559.201 423.118 559.267 423.118 559.358C409.625 565.338 394.705 568.698 379.015 568.74C369.827 570.048 367.787 573.546 366.613 575.586C366.473 575.889 366.177 576.313 366.177 576.313C366.031 576.47 365.88 576.615 365.88 576.615C364.282 579.539 363.544 581.718 362.533 584.327C361.806 586.234 361.074 588.128 359.906 590.749C351.304 609.846 334.386 636.836 287.578 649.808C279.89 651.812 275.448 659.499 277.136 667.053C277.173 667.235 277.173 667.428 277.221 667.61C278.976 674.02 284.805 678.396 291.373 678.396C292.547 678.396 293.849 678.251 295.162 677.973C338.769 666.303 362.533 642.097 374.79 624.017C380.038 616.275 384.56 607.965 388.355 598.497L388.652 597.613C404.903 596.499 420.345 592.571 434.539 586.36C447.892 602.135 471.62 612.153 499.18 612.153C501.782 612.153 504.421 612.05 507.085 611.887C508.229 611.808 509.306 611.651 510.426 611.542V685.432C510.426 693.494 516.963 700.019 525.014 700.019C533.064 700.019 539.59 693.494 539.59 685.432V603.456C540.752 602.851 541.853 602.191 542.955 601.519L630.554 617.783C631.94 618.025 633.351 618.098 634.743 617.941C671.945 614.024 700 582.851 700 545.438V488.86C699.982 471.264 693.65 454.315 682.126 441.035L682.124 441.027ZM670.817 545.424C670.817 567.214 654.969 585.471 633.627 588.672L564.725 575.87C567.872 567.868 569.228 558.898 568.563 549.194C567.988 540.896 565.887 532.567 562.019 524.995H612.476C613.457 524.995 614.401 524.898 615.334 524.71C615.775 524.625 616.211 524.45 616.653 524.317C617.119 524.178 617.597 524.063 618.051 523.881C618.578 523.663 619.074 523.36 619.571 523.082C619.898 522.9 620.249 522.761 620.551 522.543C621.338 522.023 622.095 521.417 622.779 520.721C623.475 520.025 624.08 519.275 624.607 518.494C624.807 518.191 624.946 517.852 625.127 517.531C625.412 517.029 625.715 516.526 625.932 515.988C626.114 515.534 626.229 515.062 626.374 514.583C626.507 514.142 626.677 513.718 626.768 513.276C626.949 512.35 627.052 511.4 627.052 510.419C627.052 509.438 626.949 508.482 626.768 507.562C626.683 507.108 626.507 506.684 626.374 506.254C626.229 505.788 626.12 505.298 625.932 504.85C625.715 504.311 625.406 503.815 625.127 503.306C624.946 502.986 624.807 502.647 624.607 502.344C624.08 501.557 623.481 500.807 622.779 500.117L564.451 441.789C558.761 436.099 549.524 436.099 543.834 441.789C538.144 447.491 538.144 456.716 543.834 462.417L577.277 495.854H524.985C523.581 495.854 522.243 496.114 520.948 496.489C518.369 496.047 515.663 495.745 512.843 495.551C515.978 483.99 517.685 471.878 517.685 459.403C517.685 454.142 517.388 448.61 516.662 442.926C516.505 441.606 516.238 440.329 516.045 439.028L612.227 392.874L658.762 458.543C659.065 458.985 659.404 459.403 659.761 459.802C666.885 467.822 670.808 478.149 670.808 488.863V545.422L670.817 545.424ZM460.725 571.264C456.337 567.645 453.474 563.498 452.523 559.292C452.36 558.577 452.221 557.857 452.178 557.137C451.573 548.184 459.067 541.006 463.6 537.519C468.739 533.56 475.168 530.395 482.274 528.149C488.194 526.273 494.562 525.026 501.111 524.584C501.177 524.578 501.232 524.578 501.292 524.578C503.096 524.457 504.852 524.384 506.522 524.384C527.169 524.384 538.241 533.385 539.463 551.199C540.002 559.038 538.307 565.388 534.681 570.309C534.246 570.896 533.901 571.55 533.416 572.094C528.677 577.318 520.826 580.744 510.535 582.197C508.78 582.451 506.976 582.651 505.088 582.778C485.803 584.128 469.914 578.849 460.725 571.265L460.725 571.264ZM421.036 452.249C418.548 442.522 413.627 433.763 406.932 426.688L468.776 397.01L482.244 390.546L495.397 384.238L578.027 344.591L591.362 338.193L604.696 331.789L649.64 310.228C656.783 306.59 665.609 309.471 669.235 316.65C672.873 323.829 669.979 332.625 663.085 336.116L621.802 355.927L608.468 362.331L508.653 410.222L495.518 416.53L482.256 422.891L421.036 452.249ZM365.566 495.783C365.239 495.789 364.912 495.838 364.579 495.838C348.49 495.838 335.416 482.751 335.416 466.675C335.416 459.871 337.777 453.612 341.699 448.648C344.786 444.732 348.842 441.627 353.521 439.702C356.929 438.298 360.663 437.505 364.586 437.505C369.331 437.505 373.792 438.667 377.757 440.683C386.867 445.325 393.204 454.593 393.682 465.38C393.7 465.804 393.749 466.239 393.749 466.675C393.749 473.364 391.461 479.526 387.659 484.453C382.496 491.112 374.549 495.482 365.565 495.785L365.566 495.783ZM464.145 350.002C456.96 344.385 449.182 339.531 440.974 335.414C430.031 329.93 418.318 325.802 405.976 323.454C405.001 323.26 404.014 323.139 403.04 322.975C403.579 322.261 404.136 321.559 404.644 320.833C410.794 312.062 414.886 301.759 416.218 290.616L510.379 309.453L531.746 313.726C534.403 314.253 537.006 314.973 539.555 315.784C545.172 317.564 550.486 320.021 555.463 323.054L539.555 330.68L499.314 350.002L476.464 360.964C472.572 357.09 468.486 353.386 464.146 350.002L464.145 350.002ZM294.436 350.002C289.133 354.088 284.085 358.531 279.412 363.416C275.768 367.199 271.392 368.954 265.121 367.792C248.209 364.287 229.977 363.706 213.785 365.752C175.585 370.57 140.145 389.214 114.037 418.546C97.5251 436.995 85.6429 458.775 79.0139 482.066L75.3155 481.449C67.3497 480.069 59.8621 485.492 58.5305 493.44C57.211 501.37 62.574 508.893 70.5155 510.213L72.9186 510.612L73.6389 510.733L88.0331 513.13L102.457 515.533L134.042 520.793C132.166 526.919 131.258 533.287 131.258 539.582C131.258 550.726 134.006 562.142 140.259 571.917L112.662 576.517L97.8688 578.981L83.1962 581.426L72.9363 583.133L72.6761 583.176C50.7759 580.276 29.1857 566.651 29.1857 545.417V488.839C29.1857 478.113 33.108 467.799 40.2385 459.778C40.5956 459.379 40.9346 458.961 41.2373 458.519L123.05 343.07C132.281 330.025 145.38 320.57 160.434 315.789C162.994 314.984 165.579 314.264 168.242 313.731L175.009 312.376L189.585 309.458L283.746 290.621C285.09 301.765 289.176 312.061 295.332 320.838C299.218 326.383 303.939 331.286 309.296 335.414C310.44 336.31 311.584 337.212 312.801 338.029C306.385 341.509 300.247 345.522 294.435 350.002L294.436 350.002ZM196.873 510.414C226.95 510.414 247.913 525.783 247.913 539.577C247.913 553.372 226.946 568.74 196.873 568.74C187.945 568.74 180.663 567.396 174.998 564.733C165.307 560.187 160.41 551.786 160.41 539.571C160.41 527.362 165.307 518.954 174.998 514.409C180.663 511.758 187.951 510.414 196.873 510.414ZM189.579 233.319C189.579 225.275 196.122 218.744 204.167 218.744H260.866C267.149 229.627 274.691 239.3 283.22 247.459V260.981L189.579 279.703L189.579 233.319ZM269.522 139.63C269.522 135.993 269.685 132.427 269.976 128.923C287.983 123.499 303.219 111.708 313.145 96.1878C329.07 118.003 354.754 132.251 383.772 132.251H430.186C430.325 134.69 430.465 137.13 430.465 139.63C430.465 157.662 427.069 174.658 421.119 189.579C419.079 194.7 416.73 199.578 414.109 204.154C411.107 209.414 407.748 214.299 404.086 218.742C403.504 219.444 402.905 220.116 402.306 220.788C397.3 226.496 391.756 231.411 385.794 235.358C375.007 242.506 362.852 246.55 349.996 246.55C337.145 246.55 324.984 242.506 314.21 235.358C308.241 231.411 302.703 226.496 297.685 220.788C297.098 220.11 296.486 219.444 295.905 218.742C292.225 214.299 288.878 209.414 285.875 204.154C283.255 199.566 280.906 194.693 278.866 189.579C272.904 174.658 269.52 157.661 269.52 139.63L269.522 139.63ZM290.574 32.7889C292.42 32.0322 294.315 31.3482 296.276 30.8277V54.3503C296.276 59.4711 295.453 64.3923 293.988 69.035C291.288 77.5576 286.307 85.0638 279.757 90.8623C274.213 95.7592 267.567 99.4455 260.219 101.431V77.9021C260.219 71.4374 261.52 65.2876 263.814 59.6341C268.729 47.4735 278.426 37.7526 290.575 32.7893L290.574 32.7889ZM439.794 102.072V103.089H383.773C352.619 103.089 327.172 78.5311 325.591 47.7519C325.537 46.7471 325.434 45.7666 325.434 44.7557V29.1577H366.879C406.762 29.1577 439.226 61.3594 439.745 101.121C439.751 101.448 439.793 101.751 439.793 102.072L439.794 102.072ZM510.414 233.319V279.704L416.779 260.976V247.454C425.308 239.294 432.844 229.615 439.133 218.738H495.845C503.871 218.744 510.414 225.276 510.414 233.32L510.414 233.319ZM387.604 270.019V282.604C387.604 283.366 387.537 284.111 387.489 284.861C386.309 304.539 369.971 320.199 349.991 320.199C330.015 320.199 313.672 304.546 312.493 284.861C312.438 284.117 312.378 283.366 312.378 282.604V267.477C313.733 268.082 315.095 268.651 316.475 269.202C327.044 273.427 338.309 275.727 349.991 275.727C361.68 275.727 372.933 273.427 383.507 269.202C384.881 268.658 386.255 268.089 387.605 267.477L387.604 270.019ZM248.167 670.383C248.173 670.528 248.221 670.668 248.221 670.825C248.221 678.845 241.799 685.401 233.634 685.401H233.488C225.468 685.255 219.046 678.839 219.046 670.825C219.046 670.589 219.106 670.359 219.112 670.123C219.294 666.461 220.807 663.065 223.277 660.474C226.043 657.835 229.687 656.249 233.482 656.249H233.628C241.49 656.231 247.925 662.568 248.167 670.383L248.167 670.383Z" fill="black"/>
</g>
</svg>
```

**Comment by iHiD** [comment]
### Begetter

```svg
<svg width="700" height="700" viewBox="0 0 700 700" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M48.8913 585.869C180.911 634.934 293.418 749.41 453.163 676.18C514.345 647.665 564.745 668.553 594.93 681.053C603.489 684.591 610.247 687.387 616.476 688.785C627.492 691.391 638.825 684.718 642.045 673.723L693.631 497.721C696.703 487.235 691.491 476.091 681.45 471.727L523.874 403.173C519.419 401.219 515.124 399.773 510.914 398.634C499.754 377.873 476.44 343.044 436.57 345.295C422.525 345.867 409.03 349.468 396.828 355.803C367.232 337.732 329.544 335.21 298.168 348.833C297.819 348.409 297.39 348.065 297.03 347.647C297.332 345.708 297.739 343.78 297.485 341.736C295.012 321.398 294.466 300.293 294.885 278.975C306.033 281.232 317.272 282.46 328.458 282.46C391.23 282.46 451.459 247.95 477.37 191.344C479.87 185.878 479.997 179.607 477.709 174.057C475.4 168.485 470.909 164.121 465.274 162.002C407.517 140.34 344.296 151.966 300.01 187.519C302.732 131.427 302.971 75.5511 300.54 20.7371C300.031 8.7676 289.926 -0.469618 277.913 0.0184851C265.944 0.548104 256.664 10.6746 257.195 22.6448C257.931 39.3284 258.36 56.1327 258.603 72.9967C229.506 46.3463 189.689 30.3772 146.821 30.3772C129.089 30.3772 111.505 33.11 94.5573 38.4911C88.9115 40.2918 84.2296 44.3381 81.6238 49.6768C79.0393 55.0154 78.7426 61.1803 80.7976 66.7522C102.83 125.859 163.143 165.581 230.876 165.581C239.805 165.581 248.688 164.882 257.468 163.505C256.483 190.585 255.095 217.711 252.887 244.855C252.632 246.148 252.505 247.461 252.484 248.796C252.315 249.876 252.23 250.978 252.23 252.101C252.188 252.44 252.166 252.779 252.145 253.139C252.103 253.584 252.082 254.071 252.06 254.558H252.039C250.578 276.924 251.091 298.931 252.521 320.624C205.094 308.798 150.627 334.76 140.161 383.915C108.283 387.379 80.4404 409.554 74.4557 442.703C49.3306 442.475 26.4562 457.034 13.9201 483.59C-1.94735 517.295 4.23855 564.326 48.8967 585.872L48.8913 585.869ZM423.809 195.915C397.709 227.861 353.622 244.28 310.448 237.818C336.57 206.084 380.677 189.644 423.809 195.915ZM133.618 74.4395C177.683 70.0966 221.028 88.9931 244.141 121.491C199.779 126.194 156.753 106.953 133.618 74.4395V74.4395ZM155.65 427.609C163.362 429.368 171.201 426.868 176.475 421.084C180.945 416.191 182.894 409.581 181.898 403.141C179.848 358.192 252.778 344.173 270.875 386.554C273.502 392.697 278.82 397.295 285.281 399.011C291.679 400.748 298.606 399.35 303.946 395.324C323.35 380.579 357.84 377.698 381.907 398.396C389.703 405.069 401.143 405.387 409.257 399.138C417.625 392.697 427.688 389.075 438.598 388.63C438.874 388.609 439.17 388.609 439.467 388.609C446.469 388.609 453.614 393.396 460.822 401.918C432.037 412.013 394.349 436.117 329.093 464.154L246.196 467.755C227.108 468.793 209.905 478.263 198.339 493.156L116.04 455.165C116.099 454.635 116.374 454.191 116.395 453.645C117.036 435.41 138.116 423.514 155.651 427.609L155.65 427.609ZM53.1785 502.075C55.763 496.609 62.3093 485.974 74.1724 485.974C83.3507 485.974 82.5616 488.358 183.276 534.001C183.085 537.666 183.17 541.394 183.509 545.144C186.877 581.222 215.032 608.424 249.14 608.424C251.888 608.663 337.047 597.567 359.662 594.569C372.802 592.842 374.09 591.126 449.254 567.791C460.673 564.19 467.028 551.987 463.426 540.568C459.825 529.149 447.579 522.815 436.204 526.396C359.927 550.271 361.097 550.659 354.048 551.543C351.575 551.866 251.576 564.894 248.97 565.037C237.742 565.037 227.976 554.53 226.726 541.119C225.238 525.691 235.258 511.793 248.314 511.099L334.94 507.328C346.825 506.841 425.697 466.298 432.624 462.733C476.053 440.384 488.15 434.833 506.54 442.926L646.612 503.875L606.995 639.078C573.629 625.392 509.735 601.92 434.952 636.79C296.928 700.059 201.503 596.026 65.9327 546.013C44.387 535.568 48.1793 512.705 53.1794 502.075L53.1785 502.075Z" fill="black"/>
</svg>
```

**Comment by iHiD** [comment]
### Tooling pioneer

```svg
<svg width="700" height="700" viewBox="0 0 700 700" fill="none" xmlns="http://www.w3.org/2000/svg">
<g>
<path fill-rule="evenodd" clip-rule="evenodd" d="M430.399 618.051H559.977C577.296 618.051 590.944 631.694 590.944 649.019C590.944 666.377 577.302 680.019 559.977 680.019H458.416H457.718H430.4C413.081 680.019 399.432 666.377 399.432 649.019C399.432 631.694 413.075 618.051 430.4 618.051H430.399ZM438.018 536.056H567.557C584.915 536.056 598.569 549.699 598.569 567.068C598.569 584.382 584.915 598.036 567.557 598.036L438.018 598.03C420.704 598.03 407.017 584.377 407.017 567.062C407.017 549.699 420.704 536.056 438.018 536.056V536.056ZM459.052 454.107H585.197C602.555 454.107 616.165 467.749 616.165 485.074C616.165 502.438 602.555 516.086 585.197 516.086L455.613 516.081C446.793 516.081 439.031 512.449 433.483 506.707C434.956 506.153 436.457 505.55 437.891 504.83C451.799 497.748 461.588 484.394 460.442 470.374L459.052 454.107ZM185.561 428.565V643.871L86.3798 643.865C84.3091 643.865 82.9858 642.171 82.9858 640.516L82.9802 433.898C82.9802 431.135 85.0012 430.582 86.568 430.537L185.561 428.565ZM452.022 372.117H585.187C602.545 372.117 616.155 385.76 616.155 403.118C616.155 420.437 602.545 434.086 585.187 434.086H457.303L452.022 372.117ZM428.042 326.223L440.345 470.417C440.311 476.618 437.41 484.06 428.817 486.955C405.895 494.762 390.691 487.138 384.993 465.235L363.45 382.083C360.742 368.219 339.752 373.645 344.115 387.094L365.609 470.234C369.7 485.992 377.003 498.854 388.215 504.834C393.082 507.408 398.508 508.92 404.062 509.8C393.946 526.017 381.776 536.676 366.024 543.735C349.125 551.32 327.809 554.67 301.032 554.67C287.107 554.072 287.107 575.3 301.032 574.647C329.508 574.647 353.665 571.197 374.201 561.973C379.306 559.681 384.178 557.007 388.813 553.989C387.656 558.158 387.014 562.527 387.014 567.078C387.014 582.283 393.78 595.925 404.377 605.249C389.445 614.163 379.389 630.464 379.389 649.029C379.389 660.695 383.387 671.441 390.042 680.029H260.011C241.446 680.029 217.561 669.559 205.534 650.679V422.474L281.515 342.64C289.454 334.279 299.2 330.973 308.335 329.312L411.374 310.299C422.116 308.323 427.398 318.294 428.04 326.234L428.042 326.223ZM415.274 25.5454V116.216C415.274 119.804 417.251 123.159 420.362 124.937L467.774 151.536C470.797 153.23 474.479 153.23 477.513 151.536L524.918 124.937C528.085 123.148 530.062 119.849 530.062 116.216L530.057 25.5894C566.439 46.7231 592.074 87.4683 592.118 130.461C592.019 177.309 564.644 219.814 522.023 239.144C518.213 240.843 515.86 244.708 516.143 248.838L522.2 352.144L450.321 352.139L447.985 324.543C446.971 312.966 442.88 303.093 435.355 296.787C432.542 294.451 429.331 292.756 425.981 291.599L429.148 248.877C429.475 244.752 427.172 240.798 423.362 239.043C380.685 219.708 353.267 177.264 353.167 130.411C353.167 87.3679 378.891 46.6723 415.273 25.5443L415.274 25.5454ZM425.008 0.00350725C423.806 0.0478016 422.704 0.241588 421.614 0.645765C368.327 21.591 333.179 73.1341 333.179 130.406V130.451C333.279 182.264 363.494 230.861 408.928 254.885L405.993 290.896C403.779 291.316 338.46 303.392 304.747 309.638C296.386 311.155 287.948 313.447 281.365 316.581C274.422 319.887 270.209 325.639 266.117 329.953C245.442 351.862 215.034 383.428 191.193 408.454L86.1879 410.513C80.9057 410.652 75.6734 412.39 71.0782 416.266C66.527 420.12 63 426.592 63 433.906V640.523C63 647.322 66.1671 652.97 70.303 656.962C74.428 661.01 79.854 663.85 86.3822 663.85H192.174C208.939 687.194 235.815 700 260.022 700H559.962C588.034 700 610.906 677.077 610.906 649.023C610.906 633.818 604.156 620.165 593.548 610.84C608.469 601.942 618.536 585.626 618.536 567.066C618.536 553.556 613.209 541.342 604.611 532.2C623.121 524.537 636.176 506.3 636.176 485.071C636.176 468.306 627.954 453.384 615.363 444.105C627.959 434.825 636.176 419.898 636.176 403.121C636.176 375.066 613.254 352.138 585.193 352.138H542.2L536.392 254.94C581.833 230.96 612.052 182.314 612.096 130.451L612.102 130.406C612.002 73.1781 576.965 21.73 523.668 0.784818C517.107 -1.78978 509.981 3.0327 510.025 10.0645V110.336L472.641 131.37L435.245 110.336V9.96955C435.25 4.31646 430.605 -0.140616 425.002 0.0033937L425.008 0.00350725Z" fill="black"/>
</g>
</svg>
```

**Comment by ErikSchierboom** [comment]
```ruby
bard_usernames = %w[
  aldraco
  andrerfcsantos
  andres-zartab
  angelikatyborska
  archrisv
  bethanyg
  brugnara
  ceddlyburge
  chocopowwwa
  cmcaine
  coriolinus
  efx
  erikschierboom
  gilescope
  ihid
  isaacg
  itamargal
  j08k
  jamessouth
  japatgithub
  jiegillet
  jmrunkle
  junedev
  kimolivia
  kristinaborn
  lewisclement
  limm-jk
  lxmrc
  maurelio1234
  micuffaro
  mikedamay
  mohanrajanr
  mpizenberg
  neenjaw
  nikimanoledaki
  omega-y
  ovidiu141
  pault89
  peterchu999
  pranasziaukas
  pvcarrera
  rishiosaur
  sachsom95
  saschamann
  seanchen1991
  senal
  shubhsk88
  sleeplessbyte
  stargator
  still-flow
  sudomateo
  talesdias
  tehsphinx
  thelostlambda
  ticktakto
  tompradat
  valentin-p
  verdammelt
  wneumann
  wnstj2007
  yabby1997
  yyyc514
  yzalvin
]

User.where(github_username: bard_usernames).find_each do |user|
  AwardBadgeJob.perform_later(user, :bard)
end
```

**Comment by ErikSchierboom** [comment]
```ruby
begetter_usernames = %w[
  aarti
  alexanderific
  amscotti
  andrej-makarov-skrt
  arguello
  axtens
  bdw429s
  berg-johan
  bressain
  bushidocodes
  canweriotnow
  chezwicker
  clementi
  cmc333333
  derekgottlieb
  dispader
  dog
  elorest
  erikschierboom
  etrepum
  glennj
  hankturowski
  icyrockcom
  jonboiser
  joshgoebel
  jrdnull
  junedev
  jwood803
  kenden
  kytrinyx
  larshp
  leavenha
  legalizeadulthood
  lpil
  macta
  marianfoo
  mbertheau
  mbtools
  mhelmetag
  mhinz
  mikegehard
  ozan
  paf31
  parkerl
  pclausen
  pminten
  pokrakam
  porkostomus
  qjd2413
  robinhilliard
  rpottsoh
  rubysolo
  saschamann
  sdavids13
  sgrif
  sillymoose
  sit
  sjakobi
  sleeplessbyte
  sshine
  stevejb71
  sunzenshen
  superpaintman
  szabgab
  tgecho
  thelostlambda
  tmcgilchrist
  verdammelt
]

User.where(github_username: begetter_usernames).find_each do |user|
  AwardBadgeJob.perform_later(user, :begetter)
end
```

**Comment by ErikSchierboom** [comment]
```ruby
architect_usernames = %w[
  angelikatyborska
  bethanyg
  ceddlyburge
  coriolinus
  davidgerva
  efx
  erikschierboom
  junedev
  mikedamay
  mirkoperillo
  mpizenberg
  neenjaw
  porkostomus
  sleeplessbyte
  thelostlambda
  verdammelt
  wneumann
  yawpitch
]

User.where(github_username: architect_usernames).find_each do |user|
  AwardBadgeJob.perform_later(user, :architect)
end
```

**Comment by ErikSchierboom** [comment]
```ruby
troubleshooter_usernames = %w[
  angelikatyborska
  ihid
  kotp
  kytrinyx
  nobbz
  sleeplessbyte
]

User.where(github_username: troubleshooter_usernames).find_each do |user|
  AwardBadgeJob.perform_later(user, :troubleshooter)
end
```

**Comment by ErikSchierboom** [comment]
```ruby
tooling_pioneer_usernames = %w[
  alirezaghey
  bergjohan
  ceddlyburge
  cmccandless
  coriolinus
  erikschierboom
  ihid
  mpizenberg
  seventhnadir
  sleeplessbyte
  tehsphinx
  thelostlambda
  yawpitch
]

User.where(github_username: tooling_pioneer_usernames).find_each do |user|
  AwardBadgeJob.perform_later(user, :tooling_pioneer)
end
```

**Comment by ErikSchierboom** [comment]
```ruby
moss_usernames = %w[
  andrerfcsantos
  bethanyg
  erikschierboom
  ihid
  kotp
  nobbz
  sleeplessbyte
  ynfle
]

User.where(github_username: moss_usernames).find_each do |user|
  AwardBadgeJob.perform_later(user, :moss)
end
```

**Comment by ErikSchierboom** [comment]
To update the rarity of existing badges:

```ruby
Badge.find_each do |badge|
    seed_data = badge.class.instance_variable_get("@seed_data")

    badge.update(
    name: seed_data[:name],
    rarity: seed_data[:rarity],
    icon: seed_data[:icon],
    description: seed_data[:description]
)
end
```

**Review by iHiD — APPROVED** [review]

**Pull request merged**
