### PR TITLE
[WIP] Remove deprecated discussion link from footer

### PR DESCRIPTION
**Pull request by hollenberry**
Hey there! 

It looks like the "Discuss on GitHub" footer link points to a deprecated, read-only repo. 

Should this be replaced with https://github.com/exercism/exercism.io, or does the follow icon suffice?

image

I see that the contributing guidelines note pre-agreed contributions, please close if this isn't helpful.

### CODE REVIEW

**Comment by iHiD** [comment]
Thanks for this. Rather than deleting it, could you change it to point to exercism/exercism pls?

**Comment by iHiD** [comment]
(bump @hollenberry :))

**Comment by hollenberry** [comment]
Thanks for the bump @iHiD ! Should be all set?

**Comment by iHiD** [comment]
Great. Thank you! :)

**Pull request merged**
