### PR TITLE
Correct a small typo on Dashboard

### PR DESCRIPTION
**Pull request by vivshaw**
Howdy! Spotted a little typo on the dash- `Get involve` rather than `Get involved`. Figured I'd submit a PR to fix!

### CODE REVIEW

**Review by vivshaw — COMMENTED** [review]
Howdy! Spotted a little typo on the dash- `Get involve` rather than `Get involved`. Figured I'd submit a PR to fix!

**Review by iHiD — APPROVED** [review]

**Comment by iHiD** [comment]
Thanks! I've reopened. Will merge when green (@ErikSchierboom feel free to merge if you get here first)

**Comment by vivshaw** [comment]
(The failing test _appears_ to be unrelated to this PR, but I could be wrong- apologies if I messed something up...)

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
The failing test was unrelated

**Pull request merged**
