### PR TITLE
Add modal close button

### PR DESCRIPTION
**Pull request by kntsoriano**
https://github.com/exercism/v3-beta/issues/316

### CODE REVIEW

**Comment by iHiD** [comment]
@kntsoriano I've added this. Could you check around in some modals and see if anything has changed or if stuff still looks (correctly) the same pls. I've got a really messed up local env from ETL atm so it's hard to click around.

**Comment by iHiD** [comment]
https://github.com/exercism/website/pull/1558 should fix the tests

**Comment by iHiD** [comment]
@kntsoriano You might need to look at this failing test. If it's simple, great. If it's complex, then let's leave it until after launch.

**Comment by kntsoriano** [comment]
@iHiD Test was easy to fix.

**Pull request merged**
