### PR TITLE
Added link to 'linux magazine' in index.html.haml

### PR DESCRIPTION
**Pull request by valdaarhun**
Resolves issue #[5372](https://github.com/exercism/exercism/issues/5372)

### CODE REVIEW

**Comment by SaschaMann** [comment]
@iHiD This was falsely marked as invalid.

@valdaarhun sorry for that, we're dealing with a lot of spam and had to add a bot that closes all PRs from new contributors. I don't have write access but Jeremy will be able to reopen the PR and fix the labels. Thanks for your PR!

**Comment by valdaarhun** [comment]
@SaschaMann No problem. Thanks!

**Review by iHiD — COMMENTED** [review]
Thanks. Are you able to find a link to the actual article?

**Comment by valdaarhun** [comment]
I am sorry. I didn't understand what you meant by "link to the actual article"?

**Comment by valdaarhun** [comment]
No, I couldn't find the actual article on linux magazine's website. I did however find an [article](https://www.sitepoint.com/exorcise-your-newbie-demons-by-contributing-to-exercism/) on Sitepoint's website which isn't listed on exercism's website. I also found an e-version of an [article](https://www.pressreader.com/australia/linux-format/20170606/page/38) on exercism in Linux Format's magazine on Pressreader.com.

In this PR, I have only added the link to linux magazine's home page.

**Comment by iHiD** [comment]
OK 🙂 Could you change it to link to https://www.pressreader.com/australia/linux-format/20170606/page/38 pls?

_Be aware that when you add another commit, it'll probably auto-close the issue again, due to our anti-spam guards atm. I'll reopen it when that happens._

**Comment by iHiD** [comment]
Sweet. Thank you! 💙

**Pull request merged**
