### PR TITLE
Exercised Daemons (Fixed executable architecture in Dockerfiles) 

### PR DESCRIPTION
**Pull request by TheLostLambda**

### CODE REVIEW

**Comment by iHiD** [comment]
@ErikSchierboom This was the problem...

**Comment by ErikSchierboom** [comment]
Oh my, so easy to miss! That makes total sense. I was almost starting to doubt the very foundation of Docker :D

**Comment by iHiD** [comment]
QEMU means that this gets ignored (transposed?) on some docker rubs depending on a flag. @neenjaw can explain more :)

**Comment by neenjaw** [comment]
There are some initiatives to run images from any arch on any arch (eg arm -> amd64), QEMU is a translation layer which is automatically enabled with Docker desktop (and docker with WSL2), but not docker CLI.  Which is why it worked for some, but not for all.

**Pull request merged**
