### PR TITLE
[Pending verification of bug] Hide icon when link does not exist

### LINKED ISSUE #5643: Some notifications don't have links (a without href)
image

The top two are `<a>` without `href`.

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/exercism/issues/5643.

### Reputation dropdown
Screen Shot 2021-09-10 at 2 55 14 PM
### Your Journey - Contributions list
Screen Shot 2021-09-10 at 3 00 05 PM

### CODE REVIEW

**Comment by iHiD** [comment]
@kntsoriano This isn't a valid issue I don't think. All reputation should have links. The data was just wrong.

**Comment by kntsoriano** [comment]
Okay, we should add the correct links to the tokens then. I think the code contribution and code merge dont have links.

**Comment by iHiD** [comment]
Yeah, I've already fixed this. Are you still seeing cached data?

**Comment by iHiD** [comment]
(The fix was here: https://github.com/exercism/website/pull/1810)

**Comment by kntsoriano** [comment]
I commented on the issue again.

**Comment by iHiD** [comment]
Gonna close this :)

**Pull request closed without merging**
