### PR TITLE
Style Mentoring Inbox, Queue and Dashboard

### PR DESCRIPTION
**Pull request by iHiD**
Adds initial styling for the mentor inbox, queue, and the dashboard page.

Screenshot 2020-11-30 at 23 13 35

### CODE REVIEW

**Comment by iHiD** [comment]
@kntsoriano Could you check the React on this is all ok still, and get the tests green pls? Things aren't in tables any more, and the labels on the buttons are go, so I'm not sure how to to best fix things. Thanks 🙂

**Review by kntsoriano — APPROVED** [review]

**Comment by kntsoriano** [comment]
@iHiD When I was going through `<Mentor.Inbox />`, you seem to have missed the blue dot on there.

**Review by ErikSchierboom — APPROVED** [review]
Great!

**Comment by iHiD** [comment]
> @iHiD When I was going through <Mentor.Inbox />, you seem to have missed the blue dot on there.

Thanks @kntsoriano. Great spot! I don't think it should be there. Because the inbox is all people you're mentoring, and the blue dot means "someone you've mentored", it would end up being on everyone.

**Pull request merged**
