### PR TITLE
Fixed bug where preview would not clear after comment

### PR DESCRIPTION
**Pull request by jackhughesweb**
The preview area for markdown comments would not clear after a comment had been added.

Also, I've added a system test for this issue.

Closes exercism/exercism#4192

### CODE REVIEW

**Comment by iHiD** [comment]
@jackhughesweb What do you think about adding another commit which follows your patter with  the relevant/common stuff from:

- app/views/mentor/discussion_posts/create.js.haml 
- app/views/my/discussion_posts/create.js.haml 

?

**Comment by jackhughesweb** [comment]
@iHiD A new commit or amend this commit (to remove/move it)?

**Comment by iHiD** [comment]
I think a new commit on this PR would be appropriate. I think your first commit is really nice as a first step, and it would be nice if the next one then takes it further to use your pattern instead of the original one for more stuff. Can you add tests for my/discussion and mentor/discussion for both the original commit and the new one pls?

**Comment by jackhughesweb** [comment]
@iHiD I've had a closer look at this comment bug when adding the local changes and I've found the source of the bug:

Both create.js.haml are supposed to click on the "write" tab (from master branch):
https://github.com/exercism/website/blob/edbeac35bffe6ccc826f959668cab8cacfebd14a/app/views/my/discussion_posts/create.js.haml#L6
https://github.com/exercism/website/blob/edbeac35bffe6ccc826f959668cab8cacfebd14a/app/views/mentor/discussion_posts/create.js.haml#L4

The author's discussion box works correctly, but the "write" tab is not selected on the mentor page.
This is because the `new_discussion_post` is outside of the `.discussion` element on the mentor page, so the selector for the tab button does not find any elements to select:
https://github.com/exercism/website/blob/edbeac35bffe6ccc826f959668cab8cacfebd14a/app/views/mentor/solutions/show.html.haml#L32-L38

Should I drop this previous commit with the `ajax:success` listener, and just change the selector to use `.new-discussion-post` instead, or would you like to me to keep the listener?

**Comment by iHiD** [comment]
I personally like the listener approach. What do you think?

**Comment by jackhughesweb** [comment]
@iHiD The listener approach is good, but the remote form already executes javascript after a successful submit to clear the preview area (via `create.js.haml`). It wouldn't make much sense to move the listener into this file, because it would attach a new listener after each comment, when it could just clear the preview area at this moment instead.

**Comment by iHiD** [comment]
OK. I'm happy for you to do whatever you think is best here :) Feel free to ping me on Slack if you want to discuss.

**Comment by iHiD** [comment]
Do we not need `Prism.highlightAll()` if someone adds code block into comment? (genuine question)

**Comment by jackhughesweb** [comment]
@iHiD My mistake, did not add a file to staging

**Pull request merged**
