### PR TITLE
Display information about unlocked exercises

### PR DESCRIPTION
**Pull request by strickinato**
Hi!

## What this addresses:

I discovered the issue through the `community-pr-welcome` tag here: https://github.com/exercism/exercism/issues/3967

Where @kytrinyx linked to an issue from a depricated repo here: https://github.com/exercism/DEPRECATED.v2-feedback/issues/160

Where @ErikSchierboom originally suggested the additional info.

It seems that this issue was re-reported by @ErikSchierboom here: https://github.com/exercism/exercism/issues/4016. On this issue - @nicolechalmers posted a beautiful design that @ErikSchierboom excitedly approved! This issue is labeled as `rgsoc-2018`. I'm not entirely sure what that label is about.

In any case, it _seems_ like there is consensus that this improvement should be done. Here is a screenshot of it rendered locally:

2018-08-07 at 10 10 pm

## Open question:

* I don't know the correct phrasing for an a solution that has not yet been started. I chose the word "unstarted" - but I'm not sure it's really the right phrasing.
  * **Option:** "ready to start" may be better in terms of growth mindset
  * **Maybe:** there is an agreed upon term that I wasn't able to track down in the code base. You all would know best.

Please feel free to push commits updating the wording!

## An apology

I'm sorry there isn't testing here like the other PRs I submitted. I'm happy to write tests for this, but:
  * I ran out of time this evening 😴
  * and there is still an open question about behavior 😕

❤️ Hope it looks OK! ❤️

### CODE REVIEW

**Comment by iHiD** [comment]
This is awesome. Thanks! I'll add a commit for tests and a minor tweak or two and then you can check you're happy. I think the appropriate word is "Unlocked" btw.

**Comment by iHiD** [comment]
@strickinato I've added 3 commits. Let me know if you're happy for me to merge (presuming it goes green) :)

**Comment by strickinato** [comment]
Looks great. Thanks for adding the coverage.

I would have liked to extract that JS as well - but I didn't know where.

Your commits didn't go green, but it looks like it was a class naming issue causing leaky instance variables (maybe?)

In any case, I think I fixed it - and happy for you to merge when green. 💚

**Comment by strickinato** [comment]
I just realized there may actually be a bug here 😭 -- I don't have time to fix it tonight - I was just showing my friend the changes and we realized the problem.

Maybe you want to merge even with the bug. Maybe you want to fix it. I should have time in the next few days to solve it:

2018-08-08 at 9 09 pm

**Comment by iHiD** [comment]
@strickinato I've fixed it :) This is a really cool feature. Feels really nice to use. Thank you so much for sorting it and to @nicolechalmers for the design and @ErikSchierboom for the suggestion!

**Comment by ErikSchierboom** [comment]
Yes, thanks a lot for doing this @strickinato!

**Pull request merged**
