### PR TITLE
Exclude current discussion from previous

### LINKED ISSUE #5750: The prior sessions mentored is perhaps off by one?
image

But then, when I click on it, it shows 2 instead of 1.

image

### PR DESCRIPTION
**Pull request by ErikSchierboom**
- Allow excluding of discussions when retrieving
- Exclude current discussion from previous discussions
- Add system test for current discussion exclusion

Closes https://github.com/exercism/exercism/issues/5750

### CODE REVIEW

**Review by iHiD — APPROVED** [review]
This looks great at a glance :)

**Comment by kotp** [comment]
Is this in play now? 

Because I am seeing this, which has more than 2 previous (if previous is the marker for counting) and it is more than off by one.
incorrect_number_for_previous_discussions

**Comment by kotp** [comment]
To clarify what I mean by "if previous" is the marker for counting, is that I got to this view from Boutique Inventory, and there is one future, and 4 previous discussions.  So something is not right.

**Comment by kotp** [comment]
Sorry, I got there from Simple Calculator.  Boutique was simply highlighted due to a mouse cursor position.  So it appears to be correct.  It could be nice if it were highlighting the current exercise, though, so that you can visually see prior and later discussions.

**Pull request merged**
