### PR TITLE
Remove old statuses

### PR DESCRIPTION
**Pull request by iHiD**
@kntsoriano I think these are both legacy and handled more prettily elsewhere. Can you confirm pls? For the two that are remaining, are they used? If so, how do I replicate so I can style?

### CODE REVIEW

**Comment by kntsoriano** [comment]
@iHiD These stauses are still used, so I've reverted your previous commit. In order for you to see how this look inside the editor, I've added comments to the relevant tests so you could replicate them.

The other statuses `CREATE_SUBMISSION_FAILED` and `REVERT_FAILED` appear in the same place as these messages. We currently don't have a way to replicate them via system tests and they are reserved only as error messages if something unknown to us happens (server shutting down, etc).

**Comment by iHiD** [comment]
@kntsoriano The submitting one definitely shouldn't display. That needs to be removed as it shows up every time you submit an exercise. I'm less fussed about the others.

**Comment by kntsoriano** [comment]
@iHiD This should be ready. I just added a small padding on the message in order for it to have space between the run tests button.

**Comment by iHiD** [comment]
@kntsoriano Thanks. I've added a delay so that you don't get a flash if it takes <0.3s to make the request.

**Pull request merged**
