### PR TITLE
Add mentoring notes to the site

### PR DESCRIPTION
**Pull request by iHiD**

### CODE REVIEW

**Comment by iHiD** [comment]
@kntsoriano I couldn't add any tests because I don't understand how any of the "git as a fixture" stuff works (and was on a plane without Google to help!)

Would you mind adding a commit, or explain it to me (here or Slack) and I'll do it?

I'll probably merge this in the interim as I'm desperate to get the feature live.

**Comment by michael-berger-FR** [comment]
I don't see the button to display the Mentor Notes when I mentor TwoFer on the Java track. Am I missing something?

**Comment by michael-berger-FR** [comment]
@iHiD It works perfectly fine now, thanks!

**Comment by iHiD** [comment]
Great. Thanks for letting me know :)

**Pull request merged**
