### PR TITLE
Fix panel click detection to allow clicking inside portals

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/v3-project-management/issues/191.

A pretty big change with how we handle detecting clicks outside the panel. We need to use React's synthetic events in order for us to be able to propagate the events into the portal.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by iHiD** [comment]
@kntsoriano Did you reference the wrong issue that this is fixing? The one you referenced was "apply a delay of 250ms before the fetching overlay (on ResultsZone) shows up" - which I don't think is to do with panels, and I can't see any reference to a delay here? I can't find the issue that this is aimed to fix :) Maybe this is https://github.com/exercism/v3-project-management/issues/191 ?

**Comment by iHiD** [comment]
This needs a rebase, @kntsoriano :)

**Comment by iHiD** [comment]
At some point, let's jump on a call and you can explain how this all works to me.

**Comment by kntsoriano** [comment]
@iHiD Oh yes it was https://github.com/exercism/v3-project-management/issues/191. I can explain on call :)

**Comment by iHiD** [comment]
Great! I'll merge for now and you can explain later :)

**Pull request merged**
