### PR TITLE
Prevent tooltip focus

### PR DESCRIPTION
**Pull request by neenjaw**
small tweak to prevent focus (i think)

### CODE REVIEW

**Comment by neenjaw** [comment]
@iHiD, I think this will do what you want with the tooltip.  Tried to test, dev-env spit out an error at me on the concept map page and wouldn't load (see picture) even after a complete `docker-compose down && ./bin/start --pull`, so maybe give it a quick look over live.

Screenshot from 2021-03-30 20-41-06

**Comment by iHiD** [comment]
I'll fix that, thanks. The reason you saw that was it broke/breaks if you're logged out.

**Comment by iHiD** [comment]
(Hmmm, I fixed that last night and it didn't push! 🤦)

**Comment by iHiD** [comment]
Great, so I've tested it and it works. Thanks 🙂 

Can we also remove the stuff at the bottom of `app/css/components/tooltips/concept.css` now?

**Comment by neenjaw** [comment]
If it isn't needed by the generalizations that @ErikSchierboom made, I don't see why not

**Pull request merged**
