### PR TITLE
Bump exercism-config to 0.83.0

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This will remove those annoying warnings about redis.multi﻿

### CODE REVIEW

**Comment by iHiD** [comment]
Lots of failing tests.

**Comment by ErikSchierboom** [comment]
The failures must be due to https://github.com/exercism/config/pull/45, as the `null` in the errors logs should be `assets`.

**Comment by ErikSchierboom** [comment]
Converted this to a draft pending https://github.com/exercism/config/pull/47 being merged and a new release being made.
After that, the second (temporary) commit needs to be removed.

**Comment by iHiD** [comment]
This can probably be replaced by 0.84 which we released yesterday?

**Review by iHiD — APPROVED** [review]

**Pull request merged**
