### PR TITLE
Update tooltip icon

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR addresses the open comments from https://github.com/exercism/v3/issues/2589#issuecomment-719955129

### CODE REVIEW

**Review by iHiD — APPROVED** [review]
Lovely.

**Comment by iHiD** [comment]
Want to render this in the correct place too?

(We can do this in a separate PR if you prefer)

**Review by kntsoriano — APPROVED** [review]
Nice!

**Comment by ErikSchierboom** [comment]
> Want to render this in the correct place too?
> (We can do this in a separate PR if you prefer)

Yes please :)

**Pull request merged**
