### PR TITLE
Add topics to instructions view

### PR DESCRIPTION
**Pull request by oochelz**
## Context
As I was working on exercises, I kept wanting to see what topics the current exercise was meant to cover. These are denoted as tags on the track's page, but missing on the exercise's instruction page. I thought it would be good to add it on there.

## Implementation
I used the same HAML and SCSS from where topics are displayed elsewhere.

### Large screen
lvh me_3000_my_solutions_2876f05fb5774497a51c091baf38ef2e

### iPhone 6
lvh me_3000_my_solutions_2876f05fb5774497a51c091baf38ef2e iphone 6_7_8

### CODE REVIEW

**Comment by oochelz** [comment]
Looks like this could help with this issue: https://github.com/exercism/exercism/issues/4478 
I could also add the level of difficulty to this view. Let me know what you think.

**Comment by phoenix24** [comment]
Is this good to be merged, or that additional work remains on this PR?

**Comment by iHiD** [comment]
@oochelz Hi. Thank you so much for your work on this, and sorry it didn't get a review before. As a general rule this repo doesn't accept PRs (see the `CONTRIBUTING.md` file for details). PRs that land here tend to get responded to very late, and generally don't get merged. One of the main reasons for this is that we want to avoid people doing work that we end up rejecting. Sadly, this falls into that bucket for two reasons. 

1) While the code changes themselves are great, sadly topics are not reliable enough to post onto all exercises - especially the Concept exercises, where in many cases they are just plain wrong. I'm not sure if you've seen the work we've been doing on version 3, but that focusses the exercises significantly more around concepts (a replacement for topics) and those concepts are very much becoming first-class citizens of Exercism as a result. 

2) Because of our work on v3, this repo is effectively locked unless some change is pre-agreed. I don't want to have the overhead of maintaining two codebases for the next few months while trying to juggle everything involved in v3.

So I'm sorry your effort here has been wasted. That said, we'd absolutely love your help in building out v3 of exercism if you'd like to get involved. [Here is a video] that explains what we're doing: https://www.youtube.com/watch?v=5Cj1Dr9m3GM

Thank you again for your work though.

---

@phoenix24 I imagine that answers your question.

**Comment by phoenix24** [comment]
@iHiD Thanks much. Can you help me point to the V3, where the next iteration is being developed - I tried looking up but could only come up with - `https://github.com/exercism/v3`?

**Comment by iHiD** [comment]
@phoenix24 That's the home of v3, yes :) If you'd like to get involved building out a language track, email at contribute@exercism.io and I'll get you set up :)

**Pull request closed without merging**
