### PR TITLE
Increase visibility of code samples

### PR DESCRIPTION
**Pull request by PatrickMcSweeny**
Closes exercism/exercism#4397. I darkened the text-color and text-shadow to make it the code more visible.

### CODE REVIEW

**Comment by iHiD** [comment]
Got a screenshot pls?

**Comment by PatrickMcSweeny** [comment]
I wasn't able to reproduce the bug locally, but here are some screenshots in any case.

screenshot from 2018-10-08 17-18-47
screenshot from 2018-10-08 17-16-09

**Comment by PatrickMcSweeny** [comment]
Screenshot:
screenshot from 2018-10-09 21-11-08

**Comment by iHiD** [comment]
Thanks @PatrickMcSweeny. You happy for this to go down now?

**Comment by PatrickMcSweeny** [comment]
Sure

**Comment by iHiD** [comment]
Great. Thanks :)

**Pull request merged**
