### PR TITLE
Set num_loc correctly when publishing a solution

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This fixes the issue of an incorrect num_loc if a solution had multiple iterations and was then published using a specific iteration.

### CODE REVIEW

**Comment by iHiD** [comment]
So one question with this is what happens when someone has set to publish **all** iterations, and then publish a new iteration. Will this get updated?

**Comment by ErikSchierboom** [comment]
I think that's when https://github.com/exercism/website/blob/main/app/commands/solution/publish_iteration.rb is called (which already had the right code). I'll double check.

**Comment by ErikSchierboom** [comment]
Ah no, the path is different. The num_loc gets updated in https://github.com/exercism/website/blob/main/app/jobs/calculate_lines_of_code_job.rb#L31

**Comment by iHiD** [comment]
Should we DRY this up with https://github.com/exercism/website/blob/0ea896d8a3941068bbabf5ae71e1665eb0bf1a6b/app/commands/solution/publish_iteration.rb#L2 ?

**Comment by ErikSchierboom** [comment]
I considered doing that. The only difference is that Publish also sets the published_at date. Thoughts on how to elegantly handle that?

**Comment by iHiD** [comment]
@ErikSchierboom I've DRY'd it up. Can you check you're happy pls.

**Review by ErikSchierboom — COMMENTED** [review]
Yes, nice!

**Pull request merged**
