### PR TITLE
Hide too long lines in track's example code

### PR DESCRIPTION
**Pull request by loziniak**
If it's like in Red track: https://exercism.lol/tracks/red

### CODE REVIEW

**Comment by iHiD** [comment]
Thanks. I'll need to think if we want this to scroll or not.

**Comment by iHiD** [comment]
@loziniak @ErikSchierboom Could one of you rebase this pls and I'll merge it.

**Comment by ErikSchierboom** [comment]
@loziniak Could you do the rebasing?

**Comment by loziniak** [comment]
Sure. I totally forgot about this when writing https://github.com/exercism/exercism/issues/5975! Btw what do you think about `overflow: scroll;` instead?

**Comment by iHiD** [comment]
@loziniak We seem to have an extra file in here now :)

Overflow scroll is fine, I'm agnostic :)

**Comment by loziniak** [comment]
Should be ok.

**Comment by iHiD** [comment]
Thanks :)

**Pull request merged**
