### PR TITLE
Remove reference/link to likely fake Feynman quote

### PR DESCRIPTION
**Pull request by David-Guillot**
Even though i find this quote very inspiring, and even though Feynman could have said it, searching for this quote leads to Yogi Bhajan [here](https://kundaliniresearchinstitute.org/teacher-training/) and [there](https://en.wikiquote.org/wiki/Talk:Harbhajan_Singh_Yogi). I'm not sure this is a reference you'd like to see on your website, so i just removed it. Maybe if you want to have this beautiful sentence written down, you could quote it as a Hindu proverb or something.

Sorry for being fussy about this, i was reading the `Become a mentor` page and i'm quite excited about it, then i clicked on this link and it just felt wrong.

### CODE REVIEW

**Comment by SaschaMann** [comment]
Why did this trigger just now? 🤔

**Comment by iHiD** [comment]
Screenshot 2020-10-27 at 12 58 04

**Comment by David-Guillot** [comment]
It's because I rebased/force-pushed my branch. When I saw the PR automatically closed, I just deleted my branch and my fork, as my PR was not really critical.

**Comment by iHiD** [comment]
@David-Guillot I'm still planning on removing it - I've just not got round to it yet. Sorry 😞

**Pull request closed without merging**
