### PR TITLE
Add track action dropdowns

### PR DESCRIPTION
**Pull request by kntsoriano**
https://github.com/exercism/v3-project-management/issues/228

@iHiD I've just added some stub controllers and views for the actions.

### CODE REVIEW

**Comment by iHiD** [comment]
Sweet. This is great, thanks @kntsoriano. Could you add a "Cancel" button that closes the modal on each too please.

**Comment by kntsoriano** [comment]
@iHiD I've added the cancel buttons to the modals.

**Comment by iHiD** [comment]
@kntsoriano https://www.loom.com/share/3a6c515bd2024f688e270a868acfe87f

**Comment by iHiD** [comment]
(@kntsoriano - Note that this got force-pushed)

**Comment by kntsoriano** [comment]
@iHiD This should be ready.

**Comment by iHiD** [comment]
I missed this, @kntsoriano. Will finish it tomorrow :) Thanks!

**Comment by iHiD** [comment]
Finally merged!!! Great work @kntsoriano - this one was a slog!!

**Pull request merged**
