### PR TITLE
Add ruby version

### PR DESCRIPTION
**Pull request by kntsoriano**

### CODE REVIEW

**Comment by iHiD** [comment]
I've marked this as WIP simply because I want to ensure everyone has this installed (and I don't think @kytrinyx does atm) and we need to check it's also on the servers. But I'm happy with it once those are sorted. Thanks :)

**Comment by kytrinyx** [comment]
I have 2.4.2 and 2.4.4

**Comment by iHiD** [comment]
@kntsoriano Can you merge this and test the deployment when you're next around pls :)

**Comment by iHiD** [comment]
@kntsoriano Just checking that you saw I'd assigned this one to you to merge/deploy :)

**Comment by nickborromeo** [comment]
Once this is merged in, we may need to update the [README](https://github.com/exercism/website/blob/master/README.md#ruby)

Right now it reads
>Ruby
> You need Ruby installed. We use version 2.4.

**Comment by iHiD** [comment]
@kntsoriano Could you also update the readme per @nickborromeo's comment to say we "require 2.4.4"

**Pull request merged**
