### PR TITLE
Improve lists

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/v3-project-management/issues/270.
Closes https://github.com/exercism/v3-project-management/issues/271.

@iHiD I noticed a bug in the journey page when using the filters. I didn't decide to fix this now as you've mentioned that we might change them to use `<MultipleSelect />`.

### CODE REVIEW

**Comment by iHiD** [comment]
@kntsoriano This looks great but keeps being red. I've added a small styling commit too.

**Comment by iHiD** [comment]
I think it would be worth going through the other places we `<select>` tags and replacing them too please?

```
app/javascript/components/contributing/ContributorsList.tsx:          <select
app/javascript/components/journey/BadgeResults.tsx:          <select onChange={(e) => setOrder(e.target.value)} value={order}>
app/javascript/components/journey/ContributionResults.tsx:          <select onChange={(e) => setOrder(e.target.value)} value={order}>
app/javascript/components/journey/SolutionResults.tsx:          <select onChange={(e) => setOrder(e.target.value)} value={order}>
app/javascript/components/mentoring/Sorter.tsx:      <select id={id} onChange={(e) => setOrder(e.target.value)} value={order}>
app/javascript/components/mentoring/TestimonialsList.tsx:            <select
app/javascript/components/modals/student/IterationSelector.tsx:          <select onChange={(e) => setIterationIdx(parseInt(e.target.value))}>
app/javascript/components/modals/student/finish-mentor-discussion-modal/ReportStep.tsx:                    <select ref={reasonRef} id="reason">
app/javascript/components/profile/CommunitySolutionsList.tsx:          <select
app/javascript/components/student/TracksList.tsx:            <select>
```

---

> @iHiD I noticed a bug in the journey page when using the filters. I didn't decide to fix this now as you've mentioned that we might change them to use <MultipleSelect />.

OK cool. I'll make that decision with Tai tomorrow. Thanks :)

**Comment by kntsoriano** [comment]
@iHiD I've updated the select tags, but we need to style the ff components:

1. Testimonials list
2. Mentoring inbox
3. Mentoring queue
4. Community solutions list (in profile)

**Comment by iHiD** [comment]
You force pushed over my commit! :P

**Comment by iHiD** [comment]
This should be all good now, @kntsoriano. Just needs getting green.

**Comment by kntsoriano** [comment]
@iHiD Tests have passed. We can merge now.

**Comment by iHiD** [comment]
Great. Nice work with this @kntsoriano :)

**Pull request merged**
