### PR TITLE
Finish mentor session (and assorted chaos)

### PR DESCRIPTION
**Pull request by kntsoriano**
https://github.com/exercism/v3-project-management/issues/153

@iHiD @ErikSchierboom This contains the backbone of the finish mentor session flow. Once we have the final designs, I will continue work on this.

### CODE REVIEW

**Comment by iHiD** [comment]
This is looking good, dude! Thanks :)

**Comment by iHiD** [comment]
@kntsoriano I'll be finishing this up this week. Could you rebase it pls so I can work on it? Thanks :)

**Comment by iHiD** [comment]
@kntsoriano: I've spent some time working on this. It's not finished, but it's getting there, and I'd sort of happily merge this first pass to try it.

Two jobs for you:
1. Can you ensure everything I've done is right/sensible/idiomatic/tested etc please?
2. Can you "attach" the modal to a "Finish" button the same as the mentor gets.

**Comment by kntsoriano** [comment]
@iHiD Should be ready. Let's get this merged first before I continue on https://github.com/exercism/website/pull/822.

**Comment by iHiD** [comment]
That was a big one. Well done dude - we got there! :)

**Pull request merged**
