### PR TITLE
Add IDs to document headings

### LINKED ISSUE #5984: Add IDs to docs headings
Currently, headings on exercism.org/docs pages are rendered without IDs. This makes linking to them impossible. It would be great if we could link to these specific headings.

### PR DESCRIPTION
**Pull request by ErikSchierboom**
**Ready to Merge**

---

Closes https://github.com/exercism/exercism/issues/5984

### CODE REVIEW

**Comment by iHiD** [comment]
Oooh, nice. I think we should prefix (or maybe suffix) them all though, so they don't clash with "real" ids. Let's choose (and reserve for this) a prefix? we could use `#d-...` for `doc-`

**Comment by ErikSchierboom** [comment]
What about using `h-` for heading?

**Comment by iHiD** [comment]
Sure :) Tests are red.

**Comment by ErikSchierboom** [comment]
Fixed

**Pull request merged**
