### PR TITLE
list most recent testimonials first

### PR DESCRIPTION
**Pull request by yyyc514**
- applies a sort order to the `solution_mentorships` query for
  loading testimonials for the Dashboard

### CODE REVIEW

**Comment by yyyc514** [comment]
Before:

```
+----+-------------+----------------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------------+
| id | select_type | table                | partitions | type | possible_keys       | key                 | key_len | ref   | rows | filtered | Extra       |
+----+-------------+----------------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------------+
|  1 | SIMPLE      | solution_mentorships | NULL       | ref  | fk_rails_578676d431 | fk_rails_578676d431 | 8       | const |    1 |    100.0 | Using where |
+----+-------------+----------------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------------+
```

After:

```
+----+-------------+----------------------+------------+------+---------------------+---------------------+---------+-------+------+----------+----------------------------------------------------+
| id | select_type | table                | partitions | type | possible_keys       | key                 | key_len | ref   | rows | filtered | Extra                                              |
+----+-------------+----------------------+------------+------+---------------------+---------------------+---------+-------+------+----------+----------------------------------------------------+
|  1 | SIMPLE      | solution_mentorships | NULL       | ref  | fk_rails_578676d431 | fk_rails_578676d431 | 8       | const |    1 |    100.0 | Using index condition; Using where; Using filesort |
+----+-------------+----------------------+------------+------+---------------------+---------------------+---------+-------+------+----------+----------------------------------------------------+
```

Of course I have no data, but I think the Extra is still informative.

**Comment by yyyc514** [comment]
We can add an index also if needed.  Hard to say since I have no data locally.  The need to do sort here is going to require retrieving more data than previously so it can sort it before handing back the paged query.

**Comment by yyyc514** [comment]
> Re your PR, the column you want is solutions.completed_at btw.

Isn't `solutions. updated_at` awfully close?  Esp if this is just going to change again in the future.  One index that covers BOTH these queries (from index) on the single critical table is going to be better than trying to sort solutions by a column you don't have an index for.

You're trading one fast (any tiny) query that can use the proposed index for one [HUGE one] that from where I'm sitting can't seem to use ANY index well.  (because you want to SCOPE by solution_mentorships, yet SORT by solutions).  It will use the user_id FK index against solution_memberships (cause it has no choice) but then still has to load JOIN with ALL the solutions so that it can then sort them in RAM by `completed_at`.

Does that make sense? Perhaps I need to upgrade my version of MySQL.  What version are we using in production?

**Comment by iHiD** [comment]
On the user with the most solution_mentorships with feedback (you) it takes 10ms to run:
```ruby
u.solution_mentorships.with_feedback.joins(:solution).order('solutions.completed_at desc').limit(5).offset(300)
```

So I think we're ok without the index.

> Isn't solution_mentorships.updated_at awfully close? You're using it YOURSELF for this purpose on L74:

Yeah - but this is why people complain that they're not in a logical order, because if someone comes back later and adds a comment or iteration, it will then bump the feedback to the wrong place in the queue.

**Comment by yyyc514** [comment]
> On the user with the most solution_mentorships with feedback (you) it takes 10ms to run:

Yeah, and I def want it to be fast for me. :-)  10ms is impressive.  I bet you'd be more impressed if you saw what it could do indexed. :-)  But I'll take your word it's "fast enough" for now then and go that direction with it.

> because if someone comes back later and adds a comment or iteration, it will then bump the feedback to the wrong place in the queue.

This is helpful, this is where you win with domain knowledge.  I wasn't quickly thinking of a case where the updated_at would change AFTER they left feedback... but adding more iterations (Which of course happens) makes sense... and yeah it would muck with ordering.

I'll try to swing back to this tomorrow.

Can I also turn on the "Celebration" feature that's currently disabled because of the `show_feedback_to_mentor`  field that is currently not used?

**Comment by iHiD** [comment]
> I'll try to swing back to this tomorrow.

Thanks :)

> Can I also turn on the "Celebration" feature that's currently disabled because of the show_feedback_to_mentor field that is currently not used?

Yes, if you include a screenshot, as I can't remember what it looks like.

**Comment by yyyc514** [comment]
No idea I've only seen the code, LOL.

**Comment by yyyc514** [comment]
I didn't pull up the UI so I still have no idea what Celebration stream looks like.  I did disable the query in a separate commit here since we don't need it if we're never going to show it.  I can pull that back out if necessary but seems bad form to do extra work for no reason.

**Comment by iHiD** [comment]
Thanks :) I'll deploy in a few mins.

**Pull request merged**
