### PR TITLE
Add completed concepts block

### PR DESCRIPTION
**Pull request by iHiD**
Screenshot 2021-04-21 at 19 58 27

### CODE REVIEW

**Comment by kntsoriano** [comment]
@iHiD I haven't added the exercise dots to the modal yet. I'm a bit confused of how the data from the controller will look like. Can you add it first?

**Comment by iHiD** [comment]
@kntsoriano Not had chance to do this yet. I don't think I'll get chance today, so move on to something else until I do 🙂

**Comment by kntsoriano** [comment]
@iHiD Want to merge this and add the exercise dots in as a separate issue?

**Comment by iHiD** [comment]
Yeah. Good plan.

**Comment by kntsoriano** [comment]
@iHiD Do you recall what we plan to do here?

**Comment by iHiD** [comment]
This ones on me still.

**Pull request merged**
