### PR TITLE
Add Legacy files

### PR DESCRIPTION
**Pull request by iHiD**
@kntsoriano So, this is for readonly files in the editor.

There are files that a student might have submitted via the CLI, which they need to **see** in the editor, but should **not be able to edit**. This might happen because:
- You can upload anything in the CLI and they uploaded supporting files
- They uploaded a solution and the exercise has since had the expected filename renamed, so they have a new file and an old stub.

There's various possibilities here we need to work with but for now I want to handle the basic one, which is:
- Files get a ` type` key. It can currently be `exercise`, `solution`, `legacy`. (This is done in this PR on the Ruby side)
- Files with `exercise` or `solution` behave as normal.
- Files with `legacy` are readonly. They cannot be edited.
- Files with `legacy` have an extra banner when they open. [1]
- Files with `legacy` can be deleted within the editor. This doesn't do anything outside of the editor, but means in the editor that file no longer exists and when the next submission is made it is without that file (and we should persist this fact in local storage).

Also, we also need to have support for multiple files in the editor, which I'm not sure we do atm. It doesn't seem to work for me. You should be able to submit an iteration then do `Submission.last.files.create(filename: "foobar.rb", content: "# something")` and it should appear in the editor.

Also, you might want to consider https://github.com/exercism/v3-beta/issues/145 at the same time as doing this. I think it's a good idea, but, depending on how "readonly" works it might have a different codepath entirely, as we might not want to lose the cursor position while the tests run maybe 🤷 See what you come up with 🙂 

---

[1]
Screenshot 2021-08-02 at 15 12 35
Screenshot 2021-08-02 at 15 12 37

### CODE REVIEW

**Comment by kntsoriano** [comment]
@iHiD This should be ready.

**Comment by kntsoriano** [comment]
@iHiD I'll work on https://github.com/exercism/v3-beta/issues/145 once this is merged.

**Comment by iHiD** [comment]
@kntsoriano This doesn't compile properly (asset tests fail)

**Comment by iHiD** [comment]
~I can't get this branch to work: https://www.loom.com/share/e58011935eda4bd28d5584ddd59a4564~

OK - I got it to work by clearing local storage. I think “reverting to latest iteration” should effectively do the same though. I'll open a seperate issue for this.

**Comment by iHiD** [comment]
- [ ] I think this bit needs improving.

https://www.loom.com/share/12a56f8cb47a4526850d25b6e8cb4d1a

**Comment by kntsoriano** [comment]
Done.

I've also added https://github.com/exercism/v3-project-management/issues/301 to this.

Doing the issue above made me think, though, if we want a "revert to last submission" button too?

**Comment by iHiD** [comment]
> Doing the issue above made me think, though, if we want a "revert to last submission" button too?

I think not for now. I think people can undo for code, and if they want to get a whole file back, then can go back to the iteration. But maybe as a follow-on post launch. Thanks for doing this! :)

**Comment by iHiD** [comment]
Nice work. There's still a little bug, but I'll merge and I've opened the bug as https://github.com/exercism/v3-beta/issues/153

**Pull request merged**
