### PR TITLE
Upgrade to Rails 6

### PR DESCRIPTION
**Pull request by iHiD**
This started as follows:

- Bumped Gem to 6 and ran `bundle update`
- Ran `rails app:update` and merged updates to the config files
- Fixed a deprecation warning about case_sensitivity in validator.
- Fixed an issue explained [here](https://github.com/norman/friendly_id/issues/917)

Then @kntsoriano added commits explained in the messages.

### CODE REVIEW

**Comment by kntsoriano** [comment]
@iHiD Ready for review.

**Comment by kntsoriano** [comment]
I've updated the ruby version for compatibility in Rails 6. We'll need to remember to update chef when we deploy this.

**Comment by iHiD** [comment]
Just working through the commits.

On the commit "Rename classes for autoloading compliance", rather than renaming things, could you add the HTML, SQL, and anything else to ` config/initializers/inflections.rb` please?

**Comment by kntsoriano** [comment]
Deployment checklist:

- [ ] Merge https://github.com/ThalamusAI/exercism-chef/pull/15
- [ ] Run chef on all instances
- [ ] Merge this PR
- [ ] Deploy

**Comment by iHiD** [comment]
@kntsoriano My last commit on here has made things red. Could you work it out pls :)

**Comment by iHiD** [comment]
@kntsoriano Can you check my last commit pls. Travis was failing without the mainfest change after a gem update. I removed the JS line and it worked (I presume that folder just isn't in Travis) and also checked Kaido and it's the same. So I think we're good but would appreciate a second pair of eyeballs.

**Comment by kntsoriano** [comment]
@iHiD Good catch. Rails 6 doesn't have that line in there now.

**Pull request merged**
