### PR TITLE
Add codemirror support for Gleam

### PR DESCRIPTION
**Pull request by ErikSchierboom**
image

CC @lpil

### CODE REVIEW

**Review by iHiD — APPROVED** [review]

**Review by lpil — CHANGES_REQUESTED** [review]
@giacomocavalieri it looks like the syntax highlighting isn't quite working in the screenshot there. `if` in the middle of a word is being highlighted, and the last `pub` isn't highlighted. Do you know what's up there?

**Comment by ErikSchierboom** [comment]
@lpil Do you want me to merge this? We can update later if need be.

**Comment by lpil** [comment]
I'm not sure, I'd like to hear what Giacomo thinks

**Comment by giacomocavalieri** [comment]
Sorry for the late reply! I'm currently looking into it and I'll try to come up with a fix for these bugs 👍

In the meantime could you please wait to merge this PR? There's also another bug with how strings get highlighted that would make the code quite hard to read in the online editor

**Comment by iHiD** [comment]
I've converted it to a draft so that we don't accidentally merge it. Please just ping when you're ready :)

**Comment by lpil** [comment]
Just published v1.0.1 which should resolve the problem. Please update to that version and merge, thank you! 🙏

**Comment by ErikSchierboom** [comment]
Seems to be working fine now!

Screenshot 2023-07-07 at 09 10 19

**Pull request merged**
