### PR TITLE
Rubocop improvements

### PR DESCRIPTION
**Pull request by PatrickMcSweeny**
I used rubocop to make some basic improvements to the code.

### CODE REVIEW

**Comment by iHiD** [comment]
Hi @PatrickMcSweeny. Thanks for caring about the quality of the codebase :)

- I like "Remove trailing whitespace and extra blank lines". 
- I prefer dots to be at the end of lines on so won't merge "Fix dot position in multiline method chains"
- For Rails routing and similar, I prefer symbol arrays to the shorthand syntax. So I'm ok with https://github.com/exercism/website/pull/336/files#diff-85c1566416af1aa32af8529cbe540110R26 but I don't like https://github.com/exercism/website/pull/336/files#diff-64d0b2ff83fd4db08dd47b5238715853R3 or https://github.com/exercism/website/pull/336/files#diff-d68f2f747e33e1a5678f7a8416fdedf5R2 which visually for me stop treating the things as objects and turn them into a list.

So I'd merge "Remove trailing whitespace and extra blank lines".  but probably not the other two. Want to remove the other two commits and I'll merge this PR?

**Comment by kytrinyx** [comment]
@PatrickMcSweeny I'm just catching up on all the recent PRs and noticed that you've opened a fair number that are focused on improvements to the codebase. I totally don't want to discourage you from contributing, and at the same time, I want to make sure that you've seen the note we have in the contributing guide:

> Please be aware that we only normally accept Pull Requests that have been pre-agreed or that have been marked with the community-pr-welcome label on [our issue tracker](https://github.com/exercism/exercism.io/issues?q=is%3Aissue+is%3Aopen+label%3Acommunity-pr-welcome).

The reason behind this is that we have very little bandwidth, and very much to do.

Any changes that have to do with style and readability are heavily rooted in conventions and opinions, which means that each of these require a lot of discussion... that discussion requires a clear head, and also time.

We _really_ need to focus on the issues that are a high priority. Long term, code readability and consistency will be a priority, but it's not something that is going to help our users have a better experience on the site today. Right now we're not prioritizing making things better for contributors in the codebase, we're prioritizing making things better for our users.

We're very grateful for your contributions, and would ask if possible that you keep those contributions to things that are specifically marked as `community-pr-welcome`. If you have ideas for other improvements, we'd welcome it if you open issues for them, which we can then respond to when we have a bit more time.

Our very tired brains will be very grateful 💙

**Comment by PatrickMcSweeny** [comment]
@iHiD Done

@kytrinyx I understand. I will focus on open issues from here on out.

**Comment by iHiD** [comment]
Thanks @PatrickMcSweeny :)

**Pull request merged**
