### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by iHiD**
This is GitHub's auto code analyzer. It keeps bugging me to add it. Should we?

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
As this seems to be a security feature, I'm in favor of enabling this. Individual tracks should definitely enable this at some point I feel.

I assume you just enabled JavaScript to get rid of the message? What would the disadvantage be of enabling the other support languages? That it takes a long time to run?

**Comment by iHiD** [comment]
JS is the only language that this repo uses that it supports (ie it doesn't support Ruby), so I enabled it for that. The only thing I don't know is if it really only supports node, rather than client side JS, and then if we like it we can put it on for other repos. It might be valuable for the test-runners etc, where there's actual code being executed.

I'll turn it on and we can see what happens 🤷 🙂

**Comment by ErikSchierboom** [comment]
Okay cool!

**Comment by SleeplessByte** [comment]
I think it just scans _any_ .js/.ts.

> With ATM, your JavaScript and TypeScript queries will identify more security problems. For example, we used ATM in the GitHub Security Lab to find 118 new NoSQL injection vulnerabilities across 50 JavaScript projects.

**Comment by iHiD** [comment]
Yeah, but sql injection is server side. I guess what I mean is does it look for client side vulnerabilities? As we don't use JS in production on the server it's not useful if not.

**Comment by SleeplessByte** [comment]
I need a shrug GitHub réaction.

It doesn't cost us any way right?

**Comment by iHiD** [comment]
Exactly.

**Pull request merged**
