### PR TITLE
Hide server version

### PR DESCRIPTION
**Pull request by luilver**
#### Description

Showing the server version is a security flaw:

image

Server token off directive avoids to expose it as per described here: http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens

### CODE REVIEW

**Comment by iHiD** [comment]
@dougal A second pair of eyes pls?

**Comment by joshgoebel** [comment]
Do we have a commercial ngninx subscription? Setting a custom value would be fun.

**Review by joshgoebel — APPROVED** [review]
I agree this is a good security practice.

**Comment by iHiD** [comment]
> Do we have a commercial ngninx subscription?

No :)

**Review by dougal — APPROVED** [review]
Change looks good.

Agree, is good security practice.

**Pull request merged**
