### PR TITLE
Disable form buttons upon press

### PR DESCRIPTION
**Pull request by PatrickMcSweeny**
Closes exercism/exercism#3969. I didn't have much luck writing a system test for non-ajax buttons because I don't think the test paused to check elements on the page before the form submission went through. I verified that it worked manually though.

### CODE REVIEW

**Comment by iHiD** [comment]
Hey. Thanks for this. It's a very wide-sweeping change but I think I'm good with it. I'll need to test it locally myself later this week.

One question, did you mean to delete the `.pure-button.js-disable-on-click` functionality?

**Comment by PatrickMcSweeny** [comment]
Yes, that was on purpose. It didn't work properly when I tested it locally because setTimeout didn't remove the disabled property after 20 milliseconds.

**Comment by iHiD** [comment]
Does that cause a regression for the buttons in app/views/mentor/solutions/_claim-section.html.haml or do those get covered by the form? (I can't remember how rails deals with remote buttons now-a-days)

**Comment by PatrickMcSweeny** [comment]
Yeah, I suppose it did cause a regression there so I added a new handler for that class.

**Comment by iHiD** [comment]
Great thanks. I'll have a play locally when I get chance and then merge. Thanks for sorting this - really appreciated.

**Comment by PatrickMcSweeny** [comment]
The [last asertion](https://github.com/exercism/website/pull/407/commits/a99de54b402dfee20a9b0e6739603f097673275b#diff-2b6f9d17c6e2761d17fbb5f75ee21291R22) was failing intermittently so I added in a sleep function to make sure it doesn't fire too soon, though I am beginning to think the assertion might be more trouble than its worth.

**Comment by PatrickMcSweeny** [comment]
I added the js-disable-on-click class to all of the remote links.

**Comment by iHiD** [comment]
@PatrickMcSweeny I've added a commit because the code didn't work when I ran it locally.

@kntsoriano Can you review this please and check you're happy with it. Thanks.

**Comment by kntsoriano** [comment]
@PatrickMcSweeny Thank you so much for this! Looks great! Is there a reason why you preferred this approach over using Rails' built in `data-disable-with` helper?

**Pull request merged**
