### PR TITLE
Move research into tabs

### PR DESCRIPTION
**Pull request by iHiD**
@kntsoriano I'm adding this as a PR but as much as anything its a show-and-tell for you. You can build on this PR if you like (that would probably be my preference in a way) but I'm also happy for you not to, and to do it yourself.

We want to change things on the UI a bit. The general concepts are all still the same, but things are going to move around. We're aiming for more something like this:
Screenshot 2020-01-20 at 18 55 41
Screenshot 2020-01-20 at 18 55 47
Screenshot 2020-01-20 at 18 55 53

So tabs on the LHS. And the results etc going in that div. This PR sort of starts that process for you. It adds:
1) Tabs on the LHS
2) "Run Code" now acts on the "Results" tab, rather than as a modal. 

Screenshot 2020-01-20 at 18 53 14
Screenshot 2020-01-20 at 18 53 20

We're still working on the styling, so don't worry about it too much, but the key things are:
- [x] Tabs
- [x] All status and results go into the RHS box
- [x] When the Run Code button is pressed, the Results tab is selected
- [x] If the tests fail, we scroll down to the failed test in the Results tab
- [x] The CSS class of the test run box changes for pass/fail/running, (e.g. the border colour will change).
- [x] When the Run Code button is pressed, it is disabled until the test run is cancelled etc.

There will probably be other tweaks, and there will definitely be more design changes, but that covers all the fundamentals I think.

### CODE REVIEW

**Comment by kntsoriano** [comment]
Is the submission status an overlay only on the left hand side of the screen?

**Comment by kntsoriano** [comment]
I've just pushed a first pass. When we converge on the design, I will refactor it.

**Comment by iHiD** [comment]
@kntsoriano I'll hold off merging until this is green :)

**Comment by kntsoriano** [comment]
@iHiD Green now :)

**Comment by iHiD** [comment]
@kntsoriano Sorry - can you rebase? I'll not merge any other PRs until this :)

**Pull request merged**
