### PR TITLE
Show editor error

### PR DESCRIPTION
**Pull request by kntsoriano**
https://github.com/exercism/v3-beta/issues/339

### CODE REVIEW

**Comment by iHiD** [comment]
@kntsoriano Will this mean they can resubmit the tests?

**Comment by kntsoriano** [comment]
@iHiD They still won't be able to. But they'll see an error where duplicate submissions aren't allowed. How do you think we should solve that? It's marked as a TODO in `api/submissions#create`

**Comment by iHiD** [comment]
Hmmm. I thought I'd fixed that. Strange. I'll try and remember why I thought that.

**Comment by kntsoriano** [comment]
I was thinking of the same! I think the `solution#last_valid_submission` doesn't include test runs that timed out?

**Comment by iHiD** [comment]
Yeah. I think the issue here is that the solutions were still queued. So maybe we need to think about that post-launch, and say "Your submission is still queued". The React timeout is different from the ops timeout in this situation.

**Pull request merged**
