### PR TITLE
Update to latest tracks design

### PR DESCRIPTION
**Pull request by iHiD**

### CODE REVIEW

**Comment by iHiD** [comment]
@kntsoriano The tracks page has changed a bit. I've done most of it but there are five bits I need you to for:

1. Ensuring I've removed the tabs correctly
2. Splitting the tracks into joined/unjoined (see below)
3. Adding v3 and new tags. The rule is: If it's new, show `new`, else if its concepts.size > 5, show `v3`. The HTML for both is there, they just need the pivot.
4. Populated the "touched_at" div. This is `updated_at` in the serializer.
5. Add the "5 tracks showing" next to the reset filters button.

---

This is how it looks now. So the tracks you've joined should go into one div (with class of  `joined-tracks`) and the other into `.unjoined-tracks`) If you've not joined any tracks (or joined them all!) then the other div doesn't appear.

Screenshot 2021-02-09 at 21 13 55

**Review by kntsoriano — APPROVED** [review]

**Comment by kntsoriano** [comment]
@iHiD Done. Needs some styling on your end.

**Comment by iHiD** [comment]
@kntsoriano I added a commit to this. I'll merge but you might want to check it :)

**Comment by iHiD** [comment]
The CI failed but on an unrelated test that often fails, so I'm merging. However, I couldn't test the JS as that happens after the failing test, so that might have legitimately broken. Sorry if so :)

**Pull request merged**
