### PR TITLE
Add index to speed up mentor dashboard

### PR DESCRIPTION
**Pull request by iHiD**
Closes https://github.com/exercism/exercism/issues/4680

(cc @yyyc514)

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@iHiD Do you gave any idea of the actual performance difference this will make?

**Comment by iHiD** [comment]
@ErikSchierboom Each query goes from 1.6s to 0.1s. So the total SQL time on this page goes from ~6s to ~0.5s.

The performance is personal to the person though (their tracks, number of mentored solutions, locks, etc), so it varies. But I think this is pretty repeatably about 20x faster.

**Comment by ErikSchierboom** [comment]
That's awesome! 🎉

**Comment by yyyc514** [comment]
Ba zinga!

**Pull request merged**
