### PR TITLE
Import nim mode correctly

### PR DESCRIPTION
**Pull request by kntsoriano**
https://github.com/exercism/exercism/issues/5703

I've read through the nim package and I think we just didn't import it correctly. Let's merge this and let the nim users test it?

### CODE REVIEW

**Comment by ynfle** [comment]
👍 I'm happy to test on merge

**Comment by iHiD** [comment]
Sweet. If this works, there's a number of others we need to check too.

**Comment by ynfle** [comment]
Thanks. I'm assuming it's not deployed yet.

**Comment by iHiD** [comment]
It takes 5-30mins to deploy (depending on what's changed). I'd imagine this is a 30min one.

**Comment by iHiD** [comment]
It worked. Nice work @kntsoriano! :)

**Pull request merged**
