### PR TITLE
Use website on 3020 locally and via Docker

### PR DESCRIPTION
**Pull request by iHiD**
I'm starting to map out how everything fits together. I'm going to run things from port 3020-3040 if no-one tells me that's a bad idea. I've also decided that the Dockerfile and local systems should both end up on the same port so that other local systems can reliably chat to them.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
If all you need is a port range, which will be automated, and not necessarily hit by you (lower numbers are just better DX), then there is only one reason why you would not want `3020-3040`.

If we look at the [List of TCP and UDP port numbers](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers), we can see one collision. If you look at [speedguide](https://www.speedguide.net/port.php?port=3030), there is at least one collision for each port in this range, altho I am pretty certain **you don't run any of those applications**.

User ports are 1024-49151. Pick anything that's free. Just [`netstat`](https://www.howtogeek.com/513003/how-to-use-netstat-on-linux/) and make sure you're safe, and then it's all fine.

**Review by ErikSchierboom — APPROVED** [review]
LGTM

**Comment by ErikSchierboom** [comment]
As @SleeplessByte, port collisions are the only possible reason not to use the low range, but it does indeed look like the range is not used by any applications we'll be running.

**Comment by iHiD** [comment]
Sweet. Thanks y'all! :)

**Pull request merged**
